# Generated by Django 3.0.7 on 2020-07-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='bosundia'),
            preserve_default=False,
        ),
    ]
