# Generated by Django 3.0.7 on 2020-07-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='sajib1066@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
