# Generated by Django 3.0.6 on 2020-05-12 10:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sajibnotes.helper


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('photo', models.ImageField(upload_to='notes/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_delete', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=sajibnotes.helper.get_current_user, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Category')),
                ('tag', models.ManyToManyField(to='notes.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
            preserve_default=False,
        ),
    ]
